apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: prometheus
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/reddy-2021/k8s-lab-automation-.git
    targetRevision: main
    path: gitops/helm/prometheus

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
