name: Infra + K8s Setup

on:
 workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Terraform Init & Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: Terraform Output to Inventory
        run: |
          cd terraform
          MASTER_IP=$(terraform output -raw master_ip)
          WORKER_IP=$(terraform output -raw worker_ip)

          cd ../ansiable

          cat <<EOF > inventory
          [master]
          $MASTER_IP

          [worker]
          $WORKER_IP

          [all:vars]
          ansible_user=ubuntu
          ansible_ssh_private_key_file=../terraform/my-key
          EOF

      - name: Run Ansible
        run: |
          cd ansible
          ansible-playbook -i inventory install-k8s.yml
          ansible-playbook -i inventory master.yml
          ansible-playbook -i inventory worker.yml
