name: Install Master

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.MASTER_IP }} >> ~/.ssh/known_hosts

      - name: Execute worker0 Script
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.WORKER0_IP }} 'bash -s' < scripts/worker0.sh
