name: Install Worker0

on:
  workflow_dispatch:

jobs:
  install:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

          chmod 600 ~/.ssh/id_rsa

      - name: Add Worker Host Key
        run: |
          ssh-keyscan -H ${{ secrets.WORKER0_IP }} >> ~/.ssh/known_hosts

      - name: Make Script Executable
        run: |
          chmod +x scripts/worker0.sh

      - name: Execute Worker0 Script
        run: |
          ssh \
            -i ~/.ssh/id_rsa \
            -o StrictHostKeyChecking=yes \
            ${{ secrets.SSH_USER }}@${{ secrets.WORKER0_IP }} \
            'bash -s' < scripts/worker0.sh
